kind: Service
apiVersion: v1
metadata:
# set your user name
  name: tyalon-hello-world1
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
# set your user name
    app: tyalon-hello-world1