ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/tyalon/app2'
  tag: 'chart_v2'

service:
  servicePort: 8080

probes:
  readiness:
    path: '/health/readiness'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    path: '/health/liveness'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

volume:
  mount:
    path: '/tmp/html'